
language: php

git:
    depth: 5

matrix:
    include:
        - php: 5.5
          dist: trusty
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.2
        - php: 7.3

install:
    - travis_retry composer self-update
    - travis_retry composer install

script:
    - vendor/bin/phug-dev check --report --coverage-php-version=5.6

notifications:
    slack: phug:nzXFnxhU14RWK2EQSDL0u08z

addons:
    code_climate:
        repo_token: cd1a1fbecb6b26000bcdc53d59b592735acb420dd96ce7151cd9424c39c95cf3
