
language: php

git:
  depth: 5

matrix:
  include:
    - php: 5.5
      dist: trusty
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4snapshot

install:
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - vendor/bin/phug-dev check --report --coverage-php-version=5.6

notifications:
  slack: phug:nzXFnxhU14RWK2EQSDL0u08z

addons:
  code_climate:
    repo_token: 637249f3805e62027b39a58319533f46fcfbc5274e30de7812c5c9c39d15c7ed
